# Generated by Django 6.0.6 on 2026-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='videos/')),
                ('legenda', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('PUBLICADO', 'Publicado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('premium', models.BooleanField(default=False)),
                ('agendado_para', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('erro', models.TextField(blank=True)),
            ],
        ),
    ]
