# Generated by Django 6.1 on 2026-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='erro',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='legenda',
            new_name='erro_publicacao',
        ),
        migrations.RemoveField(
            model_name='video',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='video',
            name='premium',
        ),
        migrations.AddField(
            model_name='video',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='tiktok_publish_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='agendado_para',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o vídeo deve ser publicado no TikTok. Deixe em branco para publicar imediatamente.', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='arquivo',
            field=models.FileField(upload_to='videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('agendado', 'Agendado'), ('enviando', 'Enviando para o TikTok'), ('publicado', 'Publicado'), ('erro', 'Erro ao publicar')], default='rascunho', max_length=20),
        ),
    ]
