# Generated by Django 6.1 on 2026-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_options_rename_erro_video_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='erro_publicacao',
        ),
        migrations.RemoveField(
            model_name='video',
            name='publicado_em',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.AddField(
            model_name='video',
            name='instagram_container_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='instagram_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='instagram_publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='instagram_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('enviando', 'Enviando'), ('publicado', 'Publicado'), ('erro', 'Erro ao publicar')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='postar_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='postar_tiktok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='tiktok_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='tiktok_publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='tiktok_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('enviando', 'Enviando'), ('publicado', 'Publicado'), ('erro', 'Erro ao publicar')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='agendado_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
